services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_vol:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres_vol: