version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dogHotel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dogHotel123}
      POSTGRES_DB: ${POSTGRES_DB:-playground}
    volumes:
      - postgres_vol:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres_vol: